apiVersion: v1
data:
  info.txt: "{{ .Values.production }} - {{ .Chart.AppVersion }}"
kind: ConfigMap
metadata:
  name: {{ include "multicalculatorv3.fullname" . }}-green
---
apiVersion: v1
data:
  info.txt: "{{ .Values.production }} - {{ .Chart.AppVersion }}"
kind: ConfigMap
metadata:
  name: {{ include "multicalculatorv3.fullname" . }}-blue