{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multicalculatorv3.serviceAccountName" . }}
  labels:
{{ include "multicalculatorv3.labels" . | nindent 4 }}
{{- end -}}
