{{- if .Values.dependencies.useAppInsights }}
apiVersion: v1
kind: Secret
metadata:
  name: appinsightsecret
type: Opaque
data:
  appinsightskey: {{ .Values.dependencies.appInsightsSecretValue | b64enc }}
{{- end }}
---
{{- if .Values.dependencies.useAzureRedis }}
apiVersion: v1
kind: Secret
metadata:
  name: rediscachesecret
type: Opaque
data:
  redishostkey: {{ .Values.dependencies.redisHostValue | b64enc }}
  redisauthkey: {{ .Values.dependencies.redisKeyValue | b64enc }}
{{- end }}